- name: Create Drop One Lan Environment
  hosts: localhost
  connection: local
  vars:
    resource_group: SharedEnv
    vn_name: NetworkLAN
    vn_secgroup: NetworkLAN_SecGroup
    vn_subnet: NetworkLAN_Subnet
    location: australiaeast
  tasks:
  - name: Create a resource group
    azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ vn_name }}"
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: "{{ vn_subnet }}"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{ vn_name }}"
